### PR TITLE
Edited groceries via GitHub

### PR DESCRIPTION
**Pull request by jmuhlfel**
My version of GroceryList is superior to all others.  All other grocery lists will feel its glory.

### CODE REVIEW

**Comment by jabagawee** [comment]
you misspelled "delicious"

**Comment by jmuhlfel** [comment]
No... _no_...

I... I have failed.

**Comment by calvinlsliang** [comment]
Nothing wrong with second place. ;)

**Comment by jabagawee** [comment]
go push a new version and pull request that! :D

**Pull request closed without merging**
